### ISSUE TITLE
ランキング機能を作る

### ISSUE THREAD

**Issue by tomoharutsutsumi** [tomoharutsutsumi/Comilog_Revised_Edition#10]

**Comment by tomoharutsutsumi** [comment]
@ms2sato 検索機能に関しては、DISTINCTに関しては自分で調べてみます。
複数のIDという話はイメージがつきづらいです。。。。。
joinした場合の他のテーブルのIDということでしょうか

**Comment by ms2sato** [comment]
@tomoharutsutsumi 

> joinした場合の他のテーブルのIDということでしょうか

そうですね。users、likes、comics の三つのテーブルをjoinすればIDは1レコードの中に3つありますよね。

**Comment by ms2sato** [comment]
@tomoharutsutsumi もしピンと来なかったら、とりあえずコード書いてPRしてみていいですよ。コードをベースに話す方が早いです！

**Comment by tomoharutsutsumi** [comment]
これ、@my_liked_comics に2件以上入った時に @tomoharutsutsumi が想定している結果にならないと思いますよ。

その条件で動作チェックしてみてください（そしてその状態をうまく作るのにCUIの方が楽だと思います）。モデルにメソッドを書くと良いですね。


これやります。覚えておきたいのでissueに書きます。
