### ISSUE TITLE
twitterログインを作る

### ISSUE THREAD

**Issue by tomoharutsutsumi** [tomoharutsutsumi/Comilog_Revised_Edition#25]

**Comment by tomoharutsutsumi** [comment]
@ms2sato twitterログインなのですが、emailが空であるとして、エラーが出ています。
調べて見たのですが、twitterではemailは取れないので、ダミーで対応するという情報がちらほら。。。
https://qiita.com/shitake/items/fd592bce7d0be8fadd47
こちらなども見て見たのですが、からの文字列が返ってくる状態です。nilではなく""です。
一度あげてみて、みていただいた方がよろしいでしょうか。
何卒よろしくお願いいたします。

**Comment by ms2sato** [comment]
@tomoharutsutsumi Twitterサービスの設定で、Emailを設定していなければ取得はできないと思いますが、そういうユーザーで試してますか？そして、TwitterにEmailを設定していない人は多いと思うので、それにどう対応するのかは自分で決めないといけないですよ。

Devise的にはemailは空にできないのでダミーデータを入れているんだと思います。そういう対応も一つの方法ですよって感じです。

**Comment by tomoharutsutsumi** [comment]
@ms2sato 一応自分のアカウントを利用しており、emailは入っています。
空の場合の対処は考えます。
