### ISSUE TITLE
検索機能を作る

### ISSUE THREAD

**Issue by ms2sato** [tomoharutsutsumi/Comilog_Revised_Edition#7]

**Comment by tomoharutsutsumi** [comment]
@ms2sato 取り急ぎ、自分の考えられるだけのメソッドチェーンを作ります。

**Comment by tomoharutsutsumi** [comment]
@ms2sato 
@ms2sato 取り急ぎ下記コードで作成しました。ご確認お願いします。

@search_result = Comic.where(title: params[:title]) unless params[:title] == ""
    @search_result = @search_result.or(Comic.where(type: params[:type])) unless params[:type] == ""
    @search_result = @search_result.or(Comic.where(day: params[:day])) unless params[:day] == nil
    @search_result = @search_result.or(Comic.where(origin_title: params[:origin_title])) unless params[:origin_title] == ""
    @search_result = @search_result.or(Comic.where(agetarget: params[:agetarget])) unless params[:origin_title] == nil

**Comment by ms2sato** [comment]
@tomoharutsutsumi おお、イメージは大丈夫ですね！

`brank?` を覚えると良さそうです。
`params[:title].brank?` を使うと、""でも、nil でも false が戻りますよ。

**Comment by tomoharutsutsumi** [comment]
@ms2sato すみません。自分で色々書いてて思ったんですが、AND検索にしようかなと思います。
急に変更して申し訳ないのですが、やり方結構大幅に変わりますでしょうか？

**Comment by tomoharutsutsumi** [comment]
@ms2sato 後アンドにするということは、検索の際の空欄は厳密にnilにしないと、""であるものが条件に入ってしまうということですよね。

**Comment by tomoharutsutsumi** [comment]
@ms2sato 一応自分なりにAND検索作ってみました。
@search_result = Comic.where(title: params[:title]).where(type: params[:type]).where(day: params[:day]).where(origin_title: params[:origin_title]).where(agetarget: params[:agetarget])
こんな感じかなと思ったのですが、メソッドチェーンが長い気がします。ですがチェーンにするからANDになるのかなと考えており、どうすればよいかわからない状況です（メソッドチェーンを短くするか否か）。何卒宜しくお願い申し上げます。

**Comment by tomoharutsutsumi** [comment]
@ms2sato 修正しました。
 @search_result = Comic.where(title: params[:title])
    @search_result = @search_result.where(type: params[:type])
    @search_result = @search_result.where(day: params[:day])
    @search_result = @search_result.where(origin_title: params[:origin_title])
    @search_result = @search_result.where(agetarget: params[:agetarget])
こうかなと思うのですが。。。。
ただ、paramsがblankの際に、そのparamsを無視する方法がわかりません。。。。
